// react-redux/src/components/PhotoGrid.js
import React, { PropTypes } from 'react';

import Photo from './Photo';
import FilterLink from '../containers/FilterLink';

/* eslint-disable react/prop-types */
const PhotoList = (props) => {
  if (props.posts.length === 0) {
    return <h2 style={{ textAlign: 'center' }}>Nothing here!</h2>;
  }

  return (
    <div className="photo-grid">
      {props.posts.map((post, i) => (
        <Photo
          key={post.code}
          i={i}
          post={post}
          comments={props.comments}
          increment={props.increment}
          decrement={props.decrement}
        />
      ))}
    </div>
  );
};
/* eslint-enable react/prop-types */

const PhotoGrid = props => (
  <div>
    <div className="visibility-filters">
      <FilterLink filter="ALL">All</FilterLink>
      <FilterLink filter="LIKED">Liked</FilterLink>
      <FilterLink filter="ACTIVE">Discussed</FilterLink>
    </div>

    <PhotoList
      posts={props.posts}
      comments={props.comments}
      increment={props.increment}
      decrement={props.decrement}
    />
  </div>
);

PhotoGrid.propTypes = {
  posts: PropTypes.arrayOf(PropTypes.object),
  comments: PropTypes.objectOf(PropTypes.array),
  decrement: PropTypes.func.isRequired,
  increment: PropTypes.func.isRequired
};

export default PhotoGrid;

// vue/src/components/PhotoGrid.vue
<template>
  <div>
    <div class="visibility-filters">
      <filter-button filter="ALL">All</filter-button>
      <filter-button filter="LIKED">Liked</filter-button>
      <filter-button filter="ACTIVE">Active</filter-button>
    </div>
    <div class="photo-grid">
      <photo v-for="post in posts" :key="post.code" :post="post" :comments="comments[post.code]"></photo>
    </div>
  </div>
</template>

<script>
import Photo from './Photo';
import FilterButton from './FilterButton';

export default {
  name: 'PhotoGrid',
  computed: {
    posts() {
      return this.$store.getters.visiblePosts;
    },
    comments() {
      return this.$store.state.comments;
    },
  },
  components: {
    FilterButton,
    Photo,
  },
};
</script>
