// vue/src/components/Comments.vue
<template>
  <div class="comments">
    <div v-for="(comment, index) in comments" class="comment">
      <p>
        <strong>{{ comment.user }}</strong>
        {{ comment.text }}
        <button class="remove-comment" @click.prevent="handleDeleteComment(index)">&times;</button>
      </p>
    </div>

    <form class="comment-form" @submit.prevent="handleAddComment">
      <input type="text" v-model="newAuthor" placeholder="author" />
      <input type="text" v-model="newComment" placeholder="comment" />
      <input type="submit" hidden />
    </form>
  </div>
</template>

<script>
export default {
  props: ['comments', 'postId'],

  data() {
    return {
      newAuthor: '',
      newComment: '',
    };
  },

  methods: {
    handleAddComment() {
      this.$store.commit('ADD_COMMENT', {
        postId: this.postId,
        user: this.newAuthor,
        text: this.newComment,
      });

      this.newAuthor = '';
      this.newComment = '';
    },

    handleDeleteComment(index) {
      this.$store.commit('DELETE_COMMENT', {
        postId: this.postId,
        i: index,
      });
    },
  },
};
</script>

// react-redux/src/components/Comments.js
import React, { PropTypes } from 'react';

class Comments extends React.Component {
  static propTypes = {
    removeComment: PropTypes.func.isRequired,
    addComment: PropTypes.func.isRequired,
    postComments: PropTypes.arrayOf(PropTypes.object).isRequired,
    params: PropTypes.shape({
      postId: PropTypes.string.isRequired
    }).isRequired
  }

  constructor() {
    super();

    this.renderComment = this.renderComment.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  handleSubmit(event) {
    event.preventDefault();

    const postId = this.props.params.postId;
    const author = this.commentAuthor.value;
    const message = this.commentMessage.value;

    this.props.addComment(postId, author, message);

    this.commentForm.reset();
  }

  renderComment(comment, i) {
    const { postId } = this.props.params;

    return (
      <div className="comment" key={i}>
        <p>
          <strong>{comment.user}</strong>
          {comment.text}
          <button
            className="remove-comment"
            onClick={() => { this.props.removeComment(postId, i); }}
          >&times;</button>
        </p>
      </div>
    );
  }

  render() {
    return (
      <div className="comments">
        {this.props.postComments.map(this.renderComment)}
        <form
          ref={(form) => { this.commentForm = form; }}
          className="comment-form"
          onSubmit={this.handleSubmit}
        >
          <input
            type="text"
            ref={(input) => { this.commentAuthor = input; }}
            placeholder="author"
          />
          <input
            type="text"
            ref={(input) => { this.commentMessage = input; }}
            placeholder="comment"
          />
          <input type="submit" hidden />
        </form>
      </div>
    );
  }
}

export default Comments;
