// vue/src/components/Single.vue
<template>
  <div class="single-photo">
    <photo :post="post" :comments="comments"></photo>
    <comments :comments="comments" :postId="post.code"></comments>
  </div>
</template>

<script>
import Photo from './photo';
import Comments from './comments';

export default {
  name: 'Single',

  computed: {
    post() {
      return this.$store.state.posts.find(post => (
        post.code === this.$route.params.postId
      ));
    },

    comments() {
      return this.$store.state.comments[this.post.code];
    },
  },

  components: {
    Photo,
    Comments,
  },
};
</script>

// react-redux/src/components/Single.js
import React, { PropTypes } from 'react';
import Photo from './Photo';
import Comments from './Comments';

const Single = (props) => {
  const i = props.posts.findIndex(post => (
    post.code === props.params.postId
  ));

  const post = props.posts[i];
  const postComments = props.comments[post.code] || [];

  return (
    <div className="single-photo">
      <Photo i={i} post={post} {...props} />
      <Comments postComments={postComments} {...props} />
    </div>
  );
};

Single.propTypes = {
  posts: React.PropTypes.arrayOf(React.PropTypes.object),
  comments: React.PropTypes.objectOf(PropTypes.array),
  params: React.PropTypes.shape({ postId: React.PropTypes.string.isRequired })
};

export default Single;
